# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'Twittermenti' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Twittermenti
  pod 'Swifter', :git => 'https://github.com/mattdonnelly/Swifter.git', :tag => '2.4.0'
  pod 'SwiftyJSON'
end
